version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    networks:
      - web

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - database
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  database_data:
